// Code generated by msgpack-go-gen version v0.0.2+dirty. DO NOT EDIT.

package sample

import (
	"github.com/sirkon/msgpunsafe"
	"github.com/tinylib/msgp/msgp"
	"unsafe"
)

func (d *Data) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 135)

	// Поле: name
	dst = append(dst, "\xa4name"...)
	dst = msgp.AppendString(dst, d.Name)

	// Поле: count
	dst = append(dst, "\xa5count"...)
	dst = msgp.AppendInt64(dst, int64(d.Count))

	// Поле: subs
	dst = append(dst, "\xa4subs"...)
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Subs)))
	for _, v := range d.Subs {
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v.Active)
	}

	// Поле: internal
	dst = append(dst, "\xa8internal"...)
	dst = append(dst, byte(0x80|(1&0x0f)))

	dst = append(dst, "\xa5value"...)
	dst = msgp.AppendFloat32(dst, d.Internal.Value)

	// Поле: weights
	dst = append(dst, "\xa7weights"...)
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Weights)))
	for _, v2 := range d.Weights {
		dst = msgp.AppendUint64(dst, uint64(v2))
	}

	// Поле: meta
	dst = append(dst, "\xa4meta"...)
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Meta)))
	for k, v3 := range d.Meta {
		dst = msgp.AppendString(dst, k)
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v3.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v3.Active)
	}

	// Поле: flags
	dst = append(dst, "\xa5flags"...)
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Flags)))
	for k2, v4 := range d.Flags {
		dst = msgp.AppendString(dst, k2)
		dst = msgp.AppendBool(dst, v4)
	}

	return dst, nil
}

func (d *Data) UnmarshalMsgpack(src []byte, buf *msgpunsafe.SafeBuffer) (err error) {
	defer func() {
		if r := recover(); r != nil {
			msgpunsafe.HandleError(r, &err)
		}
	}()

	ptrSrc := unsafe.Pointer(unsafe.SliceData(src))
	_ = unmarshalData(d, ptrSrc, unsafe.Add(ptrSrc, len(src)), buf)
	return nil
}

func (f *Flat) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 135)

	// Поле: name
	dst = append(dst, "\xa4name"...)
	dst = msgp.AppendString(dst, f.Name)

	// Поле: surname
	dst = append(dst, "\xa7surname"...)
	dst = msgp.AppendString(dst, f.Surname)

	// Поле: patronymic
	dst = append(dst, "\xaapatronymic"...)
	dst = msgp.AppendString(dst, f.Patronymic)

	// Поле: city
	dst = append(dst, "\xa4city"...)
	dst = msgp.AppendString(dst, f.City)

	// Поле: age
	dst = append(dst, "\xa3age"...)
	dst = msgp.AppendInt64(dst, int64(f.Age))

	// Поле: weight
	dst = append(dst, "\xa6weight"...)
	dst = msgp.AppendInt64(dst, int64(f.Weight))

	// Поле: fortune
	dst = append(dst, "\xa7fortune"...)
	dst = msgp.AppendInt64(dst, int64(f.Fortune))

	return dst, nil
}

func (f *Flat) UnmarshalMsgpack(src []byte, buf *msgpunsafe.SafeBuffer) (err error) {
	defer func() {
		if r := recover(); r != nil {
			msgpunsafe.HandleError(r, &err)
		}
	}()

	ptrSrc := unsafe.Pointer(unsafe.SliceData(src))
	_ = unmarshalFlat(f, ptrSrc, unsafe.Add(ptrSrc, len(src)), buf)
	return nil
}

func (r *Request) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 132)

	// Поле: hash
	dst = append(dst, "\xa4hash"...)
	dst = msgp.AppendString(dst, r.Hash)

	// Поле: payload
	dst = append(dst, "\xa7payload"...)
	dst = msgp.AppendString(dst, r.Value)

	return dst, nil
}

func (r *Request) UnmarshalMsgpack(src []byte, buf *msgpunsafe.SafeBuffer) (err error) {
	defer func() {
		if r := recover(); r != nil {
			msgpunsafe.HandleError(r, &err)
		}
	}()

	ptrSrc := unsafe.Pointer(unsafe.SliceData(src))
	_ = unmarshalRequest(r, ptrSrc, unsafe.Add(ptrSrc, len(src)), buf)
	return nil
}

func unmarshalData(dst *Data, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeMapHeader(src, lim)

	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeStringZC(src, lim)

		switch key {
		case "name":
			dst.Name, src = msgpunsafe.TakeString(src, lim, buf)
		case "count":
			dst.Count, src = msgpunsafe.TakeInt(src, lim)
		case "subs":
			src = unmarshalSubSlice(&dst.Subs, src, lim, buf)
		case "internal":
			src = unmarshalStruct(&dst.Internal, src, lim)
		case "weights":
			src = unmarshalUint64Slice(&dst.Weights, src, lim)
		case "meta":
			src = unmarshalStringSubMap(&dst.Meta, src, lim, buf)
		case "flags":
			src = unmarshalStringBoolMap(&dst.Flags, src, lim, buf)
		default:
			panic(msgpunsafe.ErrorUnknownField)
		}
	}

	return src
}

func unmarshalSubSlice(dst *[]Sub, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeSliceHeader(src, lim)
	result := make([]Sub, sz)
	for i := 0; i < sz; i++ {
		src = unmarshalSub(&result[i], src, lim, buf)
	}
	*dst = result

	return src
}

func unmarshalStruct(dst *struct {
	Value float32 "msgpack:\"value\""
}, src unsafe.Pointer, lim unsafe.Pointer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeMapHeader(src, lim)

	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeStringZC(src, lim)

		switch key {
		case "value":
			dst.Value, src = msgpunsafe.TakeFloat32(src, lim)
		default:
			panic(msgpunsafe.ErrorUnknownField)
		}
	}

	return src
}

func unmarshalUint64Slice(dst *[]uint64, src unsafe.Pointer, lim unsafe.Pointer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeSliceHeader(src, lim)
	result := make([]uint64, sz)
	for i := 0; i < sz; i++ {
		result[i], src = msgpunsafe.TakeUint64(src, lim)
	}
	*dst = result

	return src
}

func unmarshalStringSubMap(dst *map[string]Sub, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int
	sz, src = msgpunsafe.TakeMapHeader(src, lim)
	result := make(map[string]Sub, sz)
	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeString(src, lim, buf)

		var value Sub
		src = unmarshalSub(&value, src, lim, buf)
		result[key] = value
	}
	*dst = result

	return src
}

func unmarshalStringBoolMap(dst *map[string]bool, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int
	sz, src = msgpunsafe.TakeMapHeader(src, lim)
	result := make(map[string]bool, sz)
	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeString(src, lim, buf)

		var value bool
		value, src = msgpunsafe.TakeBool(src, lim)
		result[key] = value
	}
	*dst = result

	return src
}

func unmarshalSub(dst *Sub, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeMapHeader(src, lim)

	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeStringZC(src, lim)

		switch key {
		case "key":
			dst.Key, src = msgpunsafe.TakeString(src, lim, buf)
		case "active":
			dst.Active, src = msgpunsafe.TakeBool(src, lim)
		default:
			panic(msgpunsafe.ErrorUnknownField)
		}
	}

	return src
}

func unmarshalFlat(dst *Flat, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeMapHeader(src, lim)

	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeStringZC(src, lim)

		switch key {
		case "name":
			dst.Name, src = msgpunsafe.TakeString(src, lim, buf)
		case "surname":
			dst.Surname, src = msgpunsafe.TakeString(src, lim, buf)
		case "patronymic":
			dst.Patronymic, src = msgpunsafe.TakeString(src, lim, buf)
		case "city":
			dst.City, src = msgpunsafe.TakeString(src, lim, buf)
		case "age":
			dst.Age, src = msgpunsafe.TakeInt(src, lim)
		case "weight":
			dst.Weight, src = msgpunsafe.TakeInt(src, lim)
		case "fortune":
			dst.Fortune, src = msgpunsafe.TakeInt(src, lim)
		default:
			panic(msgpunsafe.ErrorUnknownField)
		}
	}

	return src
}

func unmarshalRequest(dst *Request, src unsafe.Pointer, lim unsafe.Pointer, buf *msgpunsafe.SafeBuffer) unsafe.Pointer {
	var sz int

	sz, src = msgpunsafe.TakeMapHeader(src, lim)

	var key string
	for i := 0; i < sz; i++ {
		key, src = msgpunsafe.TakeStringZC(src, lim)

		switch key {
		case "hash":
			dst.Hash, src = msgpunsafe.TakeString(src, lim, buf)
		case "payload":
			dst.Value, src = msgpunsafe.TakeString(src, lim, buf)
		default:
			panic(msgpunsafe.ErrorUnknownField)
		}
	}

	return src
}
