// Code generated by msgpack-go-gen version v0.0.0-20260704123545-5e63b6722f8a+dirty. DO NOT EDIT.

package sample

import (
	"fmt"
	"github.com/tinylib/msgp/msgp"
)

func (d *Data) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 135)

	// Поле: name
	dst = msgp.AppendString(dst, "name")
	dst = msgp.AppendString(dst, d.Name)

	// Поле: count
	dst = msgp.AppendString(dst, "count")
	dst = msgp.AppendInt64(dst, int64(d.Count))

	// Поле: subs
	dst = msgp.AppendString(dst, "subs")
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Subs)))
	for _, v := range d.Subs {
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v.Active)
	}

	// Поле: internal
	dst = msgp.AppendString(dst, "internal")
	dst = append(dst, byte(0x80|(1&0x0f)))

	dst = msgp.AppendString(dst, "value")
	dst = msgp.AppendFloat32(dst, d.Internal.Value)

	// Поле: weights
	dst = msgp.AppendString(dst, "weights")
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Weights)))
	for _, v2 := range d.Weights {
		dst = msgp.AppendUint64(dst, uint64(v2))
	}

	// Поле: meta
	dst = msgp.AppendString(dst, "meta")
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Meta)))
	for k, v3 := range d.Meta {
		dst = msgp.AppendString(dst, k)
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v3.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v3.Active)
	}

	// Поле: flags
	dst = msgp.AppendString(dst, "flags")
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Flags)))
	for k2, v4 := range d.Flags {
		dst = msgp.AppendString(dst, k2)
		dst = msgp.AppendBool(dst, v4)
	}

	return dst, nil
}

func (d *Data) UnmarshalMsgpack(src []byte) error {
	_, err := unmarshalData(d, src)
	return err
}

func (f *Flat) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 135)

	// Поле: name
	dst = msgp.AppendString(dst, "name")
	dst = msgp.AppendString(dst, f.Name)

	// Поле: surname
	dst = msgp.AppendString(dst, "surname")
	dst = msgp.AppendString(dst, f.Surname)

	// Поле: patronymic
	dst = msgp.AppendString(dst, "patronymic")
	dst = msgp.AppendString(dst, f.Patronymic)

	// Поле: city
	dst = msgp.AppendString(dst, "city")
	dst = msgp.AppendString(dst, f.City)

	// Поле: age
	dst = msgp.AppendString(dst, "age")
	dst = msgp.AppendInt64(dst, int64(f.Age))

	// Поле: weight
	dst = msgp.AppendString(dst, "weight")
	dst = msgp.AppendInt64(dst, int64(f.Weight))

	// Поле: fortune
	dst = msgp.AppendString(dst, "fortune")
	dst = msgp.AppendInt64(dst, int64(f.Fortune))

	return dst, nil
}

func (f *Flat) UnmarshalMsgpack(src []byte) error {
	_, err := unmarshalFlat(f, src)
	return err
}

func (r *Request) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 132)

	// Поле: hash
	dst = msgp.AppendString(dst, "hash")
	dst = msgp.AppendString(dst, r.Hash)

	// Поле: payload
	dst = msgp.AppendString(dst, "payload")
	dst = msgp.AppendString(dst, r.Value)

	return dst, nil
}

func (r *Request) UnmarshalMsgpack(src []byte) error {
	_, err := unmarshalRequest(r, src)
	return err
}

func unmarshalData(dst *Data, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail

	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		switch key {
		case "name":
			srcOffset, dst.Name, err = unmarshalString(src)
		case "count":
			srcOffset, dst.Count, err = unmarshalInt(src)
		case "subs":
			srcOffset, err = unmarshalSubSlice(&dst.Subs, src)
		case "internal":
			srcOffset, err = unmarshalStruct(&dst.Internal, src)
		case "weights":
			srcOffset, err = unmarshalUint64Slice(&dst.Weights, src)
		case "meta":
			srcOffset, err = unmarshalStringSubMap(&dst.Meta, src)
		case "flags":
			srcOffset, err = unmarshalStringBoolMap(&dst.Flags, src)
		default:
			return len(orig) - len(src), fmt.Errorf("unknown field %q", key)
		}
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}

	return len(orig) - len(src), nil
}

func unmarshalString(src []byte) (offset int, value string, err error) {
	var raw string
	var tail []byte
	raw, tail, err = msgp.ReadStringBytes(src)
	if err != nil {
		return 0, value, err
	}
	return len(src) - len(tail), string(raw), nil
}

func unmarshalInt(src []byte) (offset int, value int, err error) {
	var raw int
	var tail []byte
	raw, tail, err = msgp.ReadIntBytes(src)
	if err != nil {
		return 0, value, err
	}
	return len(src) - len(tail), int(raw), nil
}

func unmarshalSubSlice(dst *[]Sub, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadArrayHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail
	result := make([]Sub, sz)
	var srcOffset int
	for i := uint32(0); i < sz; i++ {
		srcOffset, err = unmarshalSub(&result[i], src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}
	*dst = result

	return len(orig) - len(src), nil
}

func unmarshalStruct(dst *struct {
	Value float32 "msgpack:\"value\""
}, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail

	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		switch key {
		case "value":
			srcOffset, dst.Value, err = unmarshalFloat32(src)
		default:
			return len(orig) - len(src), fmt.Errorf("unknown field %q", key)
		}
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}

	return len(orig) - len(src), nil
}

func unmarshalUint64Slice(dst *[]uint64, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadArrayHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail
	result := make([]uint64, sz)
	var srcOffset int
	for i := uint32(0); i < sz; i++ {
		srcOffset, result[i], err = unmarshalUint64(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}
	*dst = result

	return len(orig) - len(src), nil
}

func unmarshalStringSubMap(dst *map[string]Sub, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail
	result := make(map[string]Sub, sz)
	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		var value Sub
		srcOffset, err = unmarshalSub(&value, src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
		result[key] = value
	}
	*dst = result

	return len(orig) - len(src), nil
}

func unmarshalStringBoolMap(dst *map[string]bool, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail
	result := make(map[string]bool, sz)
	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		var value bool
		srcOffset, value, err = unmarshalBool(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
		result[key] = value
	}
	*dst = result

	return len(orig) - len(src), nil
}

func unmarshalSub(dst *Sub, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail

	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		switch key {
		case "key":
			srcOffset, dst.Key, err = unmarshalString(src)
		case "active":
			srcOffset, dst.Active, err = unmarshalBool(src)
		default:
			return len(orig) - len(src), fmt.Errorf("unknown field %q", key)
		}
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}

	return len(orig) - len(src), nil
}

func unmarshalFloat32(src []byte) (offset int, value float32, err error) {
	var raw float32
	var tail []byte
	raw, tail, err = msgp.ReadFloat32Bytes(src)
	if err != nil {
		return 0, value, err
	}
	return len(src) - len(tail), float32(raw), nil
}

func unmarshalUint64(src []byte) (offset int, value uint64, err error) {
	var raw uint64
	var tail []byte
	raw, tail, err = msgp.ReadUint64Bytes(src)
	if err != nil {
		return 0, value, err
	}
	return len(src) - len(tail), uint64(raw), nil
}

func unmarshalBool(src []byte) (offset int, value bool, err error) {
	var raw bool
	var tail []byte
	raw, tail, err = msgp.ReadBoolBytes(src)
	if err != nil {
		return 0, value, err
	}
	return len(src) - len(tail), bool(raw), nil
}

func unmarshalFlat(dst *Flat, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail

	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		switch key {
		case "name":
			srcOffset, dst.Name, err = unmarshalString(src)
		case "surname":
			srcOffset, dst.Surname, err = unmarshalString(src)
		case "patronymic":
			srcOffset, dst.Patronymic, err = unmarshalString(src)
		case "city":
			srcOffset, dst.City, err = unmarshalString(src)
		case "age":
			srcOffset, dst.Age, err = unmarshalInt(src)
		case "weight":
			srcOffset, dst.Weight, err = unmarshalInt(src)
		case "fortune":
			srcOffset, dst.Fortune, err = unmarshalInt(src)
		default:
			return len(orig) - len(src), fmt.Errorf("unknown field %q", key)
		}
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}

	return len(orig) - len(src), nil
}

func unmarshalRequest(dst *Request, src []byte) (int, error) {
	orig := src
	sz, tail, err := msgp.ReadMapHeaderBytes(src)
	if err != nil {
		return 0, err
	}
	src = tail

	var srcOffset int
	var key string
	for i := uint32(0); i < sz; i++ {
		srcOffset, key, err = unmarshalString(src)
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]

		switch key {
		case "hash":
			srcOffset, dst.Hash, err = unmarshalString(src)
		case "payload":
			srcOffset, dst.Value, err = unmarshalString(src)
		default:
			return len(orig) - len(src), fmt.Errorf("unknown field %q", key)
		}
		if err != nil {
			return 0, err
		}
		src = src[srcOffset:]
	}

	return len(orig) - len(src), nil
}
