// Code generated by msgpack-go-gen version v0.0.0-20260704064807-0cc9f4bb3bd1+dirty. DO NOT EDIT.

package sample

import (
	"github.com/tinylib/msgp/msgp"
)

func (d *Data) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 135)

	// Поле: name
	dst = msgp.AppendString(dst, "name")
	dst = msgp.AppendString(dst, d.Name)

	// Поле: count
	dst = msgp.AppendString(dst, "count")
	dst = msgp.AppendInt64(dst, int64(d.Count))

	// Поле: subs
	dst = msgp.AppendString(dst, "subs")
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Subs)))
	for _, v := range d.Subs {
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v.Active)
	}

	// Поле: internal
	dst = msgp.AppendString(dst, "internal")
	dst = append(dst, byte(0x80|(1&0x0f)))

	dst = msgp.AppendString(dst, "value")
	dst = msgp.AppendFloat32(dst, d.Internal.Value)

	// Поле: weights
	dst = msgp.AppendString(dst, "weights")
	dst = msgp.AppendArrayHeader(dst, uint32(len(d.Weights)))
	for _, v2 := range d.Weights {
		dst = msgp.AppendUint64(dst, uint64(v2))
	}

	// Поле: meta
	dst = msgp.AppendString(dst, "meta")
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Meta)))
	for k, v3 := range d.Meta {
		dst = msgp.AppendString(dst, k)
		dst = append(dst, byte(0x80|(2&0x0f)))

		dst = msgp.AppendString(dst, "key")
		dst = msgp.AppendString(dst, v3.Key)

		dst = msgp.AppendString(dst, "active")
		dst = msgp.AppendBool(dst, v3.Active)
	}

	// Поле: flags
	dst = msgp.AppendString(dst, "flags")
	dst = msgp.AppendMapHeader(dst, uint32(len(d.Flags)))
	for k2, v4 := range d.Flags {
		dst = msgp.AppendString(dst, k2)
		dst = msgp.AppendBool(dst, v4)
	}

	return dst, nil
}
func (r *Request) MarshalMsgpack(dst []byte) ([]byte, error) {
	dst = append(dst, 132)

	// Поле: hash
	dst = msgp.AppendString(dst, "hash")
	dst = msgp.AppendString(dst, r.Hash)

	// Поле: payload
	dst = msgp.AppendString(dst, "payload")
	dst = msgp.AppendString(dst, r.Value)

	return dst, nil
}
