// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package sample

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Data) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "count":
			z.Count, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		case "subs":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Subs")
				return
			}
			if cap(z.Subs) >= int(zb0002) {
				z.Subs = (z.Subs)[:zb0002]
			} else {
				z.Subs = make([]Sub, zb0002)
			}
			for za0001 := range z.Subs {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Subs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Subs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						z.Subs[za0001].Key, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001, "Key")
							return
						}
					case "active":
						z.Subs[za0001].Active, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001, "Active")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001)
							return
						}
					}
				}
			}
		case "internal":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Internal")
				return
			}
			for zb0004 > 0 {
				zb0004--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Internal")
					return
				}
				switch msgp.UnsafeString(field) {
				case "value":
					z.Internal.Value, err = dc.ReadFloat32()
					if err != nil {
						err = msgp.WrapError(err, "Internal", "Value")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Internal")
						return
					}
				}
			}
		case "weights":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Weights")
				return
			}
			if cap(z.Weights) >= int(zb0005) {
				z.Weights = (z.Weights)[:zb0005]
			} else {
				z.Weights = make([]uint64, zb0005)
			}
			for za0002 := range z.Weights {
				z.Weights[za0002], err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Weights", za0002)
					return
				}
			}
		case "meta":
			var zb0006 uint32
			zb0006, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
			if z.Meta == nil {
				z.Meta = make(map[string]Sub, zb0006)
			} else if len(z.Meta) > 0 {
				clear(z.Meta)
			}
			for zb0006 > 0 {
				zb0006--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Meta")
					return
				}
				var za0004 Sub
				var zb0007 uint32
				zb0007, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Meta", za0003)
					return
				}
				for zb0007 > 0 {
					zb0007--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Meta", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						za0004.Key, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003, "Key")
							return
						}
					case "active":
						za0004.Active, err = dc.ReadBool()
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003, "Active")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003)
							return
						}
					}
				}
				z.Meta[za0003] = za0004
			}
		case "flags":
			var zb0008 uint32
			zb0008, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Flags")
				return
			}
			if z.Flags == nil {
				z.Flags = make(map[string]bool, zb0008)
			} else if len(z.Flags) > 0 {
				clear(z.Flags)
			}
			for zb0008 > 0 {
				zb0008--
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Flags")
					return
				}
				var za0006 bool
				za0006, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "Flags", za0005)
					return
				}
				z.Flags[za0005] = za0006
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Data) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "name"
	err = en.Append(0x87, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "count"
	err = en.Append(0xa5, 0x63, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Count)
	if err != nil {
		err = msgp.WrapError(err, "Count")
		return
	}
	// write "subs"
	err = en.Append(0xa4, 0x73, 0x75, 0x62, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Subs)))
	if err != nil {
		err = msgp.WrapError(err, "Subs")
		return
	}
	for za0001 := range z.Subs {
		// map header, size 2
		// write "key"
		err = en.Append(0x82, 0xa3, 0x6b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.Subs[za0001].Key)
		if err != nil {
			err = msgp.WrapError(err, "Subs", za0001, "Key")
			return
		}
		// write "active"
		err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
		if err != nil {
			return
		}
		err = en.WriteBool(z.Subs[za0001].Active)
		if err != nil {
			err = msgp.WrapError(err, "Subs", za0001, "Active")
			return
		}
	}
	// write "internal"
	err = en.Append(0xa8, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c)
	if err != nil {
		return
	}
	// map header, size 1
	// write "value"
	err = en.Append(0x81, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat32(z.Internal.Value)
	if err != nil {
		err = msgp.WrapError(err, "Internal", "Value")
		return
	}
	// write "weights"
	err = en.Append(0xa7, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Weights)))
	if err != nil {
		err = msgp.WrapError(err, "Weights")
		return
	}
	for za0002 := range z.Weights {
		err = en.WriteUint64(z.Weights[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Weights", za0002)
			return
		}
	}
	// write "meta"
	err = en.Append(0xa4, 0x6d, 0x65, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Meta)))
	if err != nil {
		err = msgp.WrapError(err, "Meta")
		return
	}
	for za0003, za0004 := range z.Meta {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "Meta")
			return
		}
		// map header, size 2
		// write "key"
		err = en.Append(0x82, 0xa3, 0x6b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(za0004.Key)
		if err != nil {
			err = msgp.WrapError(err, "Meta", za0003, "Key")
			return
		}
		// write "active"
		err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
		if err != nil {
			return
		}
		err = en.WriteBool(za0004.Active)
		if err != nil {
			err = msgp.WrapError(err, "Meta", za0003, "Active")
			return
		}
	}
	// write "flags"
	err = en.Append(0xa5, 0x66, 0x6c, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Flags)))
	if err != nil {
		err = msgp.WrapError(err, "Flags")
		return
	}
	for za0005, za0006 := range z.Flags {
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "Flags")
			return
		}
		err = en.WriteBool(za0006)
		if err != nil {
			err = msgp.WrapError(err, "Flags", za0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Data) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "name"
	o = append(o, 0x87, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "count"
	o = append(o, 0xa5, 0x63, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.Count)
	// string "subs"
	o = append(o, 0xa4, 0x73, 0x75, 0x62, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Subs)))
	for za0001 := range z.Subs {
		// map header, size 2
		// string "key"
		o = append(o, 0x82, 0xa3, 0x6b, 0x65, 0x79)
		o = msgp.AppendString(o, z.Subs[za0001].Key)
		// string "active"
		o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
		o = msgp.AppendBool(o, z.Subs[za0001].Active)
	}
	// string "internal"
	o = append(o, 0xa8, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c)
	// map header, size 1
	// string "value"
	o = append(o, 0x81, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
	o = msgp.AppendFloat32(o, z.Internal.Value)
	// string "weights"
	o = append(o, 0xa7, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Weights)))
	for za0002 := range z.Weights {
		o = msgp.AppendUint64(o, z.Weights[za0002])
	}
	// string "meta"
	o = append(o, 0xa4, 0x6d, 0x65, 0x74, 0x61)
	o = msgp.AppendMapHeader(o, uint32(len(z.Meta)))
	for za0003, za0004 := range z.Meta {
		o = msgp.AppendString(o, za0003)
		// map header, size 2
		// string "key"
		o = append(o, 0x82, 0xa3, 0x6b, 0x65, 0x79)
		o = msgp.AppendString(o, za0004.Key)
		// string "active"
		o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
		o = msgp.AppendBool(o, za0004.Active)
	}
	// string "flags"
	o = append(o, 0xa5, 0x66, 0x6c, 0x61, 0x67, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Flags)))
	for za0005, za0006 := range z.Flags {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendBool(o, za0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Data) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "count":
			z.Count, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		case "subs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Subs")
				return
			}
			if cap(z.Subs) >= int(zb0002) {
				z.Subs = (z.Subs)[:zb0002]
			} else {
				z.Subs = make([]Sub, zb0002)
			}
			for za0001 := range z.Subs {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Subs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Subs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						z.Subs[za0001].Key, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001, "Key")
							return
						}
					case "active":
						z.Subs[za0001].Active, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001, "Active")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Subs", za0001)
							return
						}
					}
				}
			}
		case "internal":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Internal")
				return
			}
			for zb0004 > 0 {
				zb0004--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Internal")
					return
				}
				switch msgp.UnsafeString(field) {
				case "value":
					z.Internal.Value, bts, err = msgp.ReadFloat32Bytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Internal", "Value")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Internal")
						return
					}
				}
			}
		case "weights":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Weights")
				return
			}
			if cap(z.Weights) >= int(zb0005) {
				z.Weights = (z.Weights)[:zb0005]
			} else {
				z.Weights = make([]uint64, zb0005)
			}
			for za0002 := range z.Weights {
				z.Weights[za0002], bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Weights", za0002)
					return
				}
			}
		case "meta":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
			if z.Meta == nil {
				z.Meta = make(map[string]Sub, zb0006)
			} else if len(z.Meta) > 0 {
				clear(z.Meta)
			}
			for zb0006 > 0 {
				var za0004 Sub
				zb0006--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Meta")
					return
				}
				var zb0007 uint32
				zb0007, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Meta", za0003)
					return
				}
				for zb0007 > 0 {
					zb0007--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Meta", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					case "key":
						za0004.Key, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003, "Key")
							return
						}
					case "active":
						za0004.Active, bts, err = msgp.ReadBoolBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003, "Active")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Meta", za0003)
							return
						}
					}
				}
				z.Meta[za0003] = za0004
			}
		case "flags":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Flags")
				return
			}
			if z.Flags == nil {
				z.Flags = make(map[string]bool, zb0008)
			} else if len(z.Flags) > 0 {
				clear(z.Flags)
			}
			for zb0008 > 0 {
				var za0006 bool
				zb0008--
				var za0005 string
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Flags")
					return
				}
				za0006, bts, err = msgp.ReadBoolBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Flags", za0005)
					return
				}
				z.Flags[za0005] = za0006
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Data) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.IntSize + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Subs {
		s += 1 + 4 + msgp.StringPrefixSize + len(z.Subs[za0001].Key) + 7 + msgp.BoolSize
	}
	s += 9 + 1 + 6 + msgp.Float32Size + 8 + msgp.ArrayHeaderSize + (len(z.Weights) * (msgp.Uint64Size)) + 5 + msgp.MapHeaderSize
	if z.Meta != nil {
		for za0003, za0004 := range z.Meta {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + 1 + 4 + msgp.StringPrefixSize + len(za0004.Key) + 7 + msgp.BoolSize
		}
	}
	s += 6 + msgp.MapHeaderSize
	if z.Flags != nil {
		for za0005, za0006 := range z.Flags {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.BoolSize
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Flat) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "surname":
			z.Surname, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Surname")
				return
			}
		case "patronymic":
			z.Patronymic, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Patronymic")
				return
			}
		case "city":
			z.City, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "City")
				return
			}
		case "age":
			z.Age, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Age")
				return
			}
		case "weight":
			z.Weight, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "fortune":
			z.Fortune, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Fortune")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Flat) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "name"
	err = en.Append(0x87, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "surname"
	err = en.Append(0xa7, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Surname)
	if err != nil {
		err = msgp.WrapError(err, "Surname")
		return
	}
	// write "patronymic"
	err = en.Append(0xaa, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63)
	if err != nil {
		return
	}
	err = en.WriteString(z.Patronymic)
	if err != nil {
		err = msgp.WrapError(err, "Patronymic")
		return
	}
	// write "city"
	err = en.Append(0xa4, 0x63, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.City)
	if err != nil {
		err = msgp.WrapError(err, "City")
		return
	}
	// write "age"
	err = en.Append(0xa3, 0x61, 0x67, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Age)
	if err != nil {
		err = msgp.WrapError(err, "Age")
		return
	}
	// write "weight"
	err = en.Append(0xa6, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Weight)
	if err != nil {
		err = msgp.WrapError(err, "Weight")
		return
	}
	// write "fortune"
	err = en.Append(0xa7, 0x66, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Fortune)
	if err != nil {
		err = msgp.WrapError(err, "Fortune")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Flat) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "name"
	o = append(o, 0x87, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "surname"
	o = append(o, 0xa7, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Surname)
	// string "patronymic"
	o = append(o, 0xaa, 0x70, 0x61, 0x74, 0x72, 0x6f, 0x6e, 0x79, 0x6d, 0x69, 0x63)
	o = msgp.AppendString(o, z.Patronymic)
	// string "city"
	o = append(o, 0xa4, 0x63, 0x69, 0x74, 0x79)
	o = msgp.AppendString(o, z.City)
	// string "age"
	o = append(o, 0xa3, 0x61, 0x67, 0x65)
	o = msgp.AppendInt(o, z.Age)
	// string "weight"
	o = append(o, 0xa6, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendInt(o, z.Weight)
	// string "fortune"
	o = append(o, 0xa7, 0x66, 0x6f, 0x72, 0x74, 0x75, 0x6e, 0x65)
	o = msgp.AppendInt(o, z.Fortune)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Flat) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "surname":
			z.Surname, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Surname")
				return
			}
		case "patronymic":
			z.Patronymic, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Patronymic")
				return
			}
		case "city":
			z.City, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "City")
				return
			}
		case "age":
			z.Age, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Age")
				return
			}
		case "weight":
			z.Weight, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		case "fortune":
			z.Fortune, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Fortune")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Flat) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 8 + msgp.StringPrefixSize + len(z.Surname) + 11 + msgp.StringPrefixSize + len(z.Patronymic) + 5 + msgp.StringPrefixSize + len(z.City) + 4 + msgp.IntSize + 7 + msgp.IntSize + 8 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Request) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "hash":
			z.Hash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "payload":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Request) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "hash"
	err = en.Append(0x82, 0xa4, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hash)
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	// write "payload"
	err = en.Append(0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Request) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "hash"
	o = append(o, 0x82, 0xa4, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.Hash)
	// string "payload"
	o = append(o, 0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	o = msgp.AppendString(o, z.Value)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Request) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "hash":
			z.Hash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "payload":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Request) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Hash) + 8 + msgp.StringPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *RequestCheck) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "funcname":
			z.FuncName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "reqid":
			z.ReqID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ReqID")
				return
			}
		case "hash":
			z.Hash, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "payload":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *RequestCheck) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "funcname"
	err = en.Append(0x84, 0xa8, 0x66, 0x75, 0x6e, 0x63, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.FuncName)
	if err != nil {
		err = msgp.WrapError(err, "FuncName")
		return
	}
	// write "reqid"
	err = en.Append(0xa5, 0x72, 0x65, 0x71, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ReqID)
	if err != nil {
		err = msgp.WrapError(err, "ReqID")
		return
	}
	// write "hash"
	err = en.Append(0xa4, 0x68, 0x61, 0x73, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hash)
	if err != nil {
		err = msgp.WrapError(err, "Hash")
		return
	}
	// write "payload"
	err = en.Append(0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *RequestCheck) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "funcname"
	o = append(o, 0x84, 0xa8, 0x66, 0x75, 0x6e, 0x63, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.FuncName)
	// string "reqid"
	o = append(o, 0xa5, 0x72, 0x65, 0x71, 0x69, 0x64)
	o = msgp.AppendString(o, z.ReqID)
	// string "hash"
	o = append(o, 0xa4, 0x68, 0x61, 0x73, 0x68)
	o = msgp.AppendString(o, z.Hash)
	// string "payload"
	o = append(o, 0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
	o = msgp.AppendString(o, z.Value)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *RequestCheck) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "funcname":
			z.FuncName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "reqid":
			z.ReqID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReqID")
				return
			}
		case "hash":
			z.Hash, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Hash")
				return
			}
		case "payload":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RequestCheck) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.FuncName) + 6 + msgp.StringPrefixSize + len(z.ReqID) + 5 + msgp.StringPrefixSize + len(z.Hash) + 8 + msgp.StringPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Sub) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "key":
			z.Key, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "active":
			z.Active, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Sub) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "key"
	err = en.Append(0x82, 0xa3, 0x6b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Key)
	if err != nil {
		err = msgp.WrapError(err, "Key")
		return
	}
	// write "active"
	err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Active)
	if err != nil {
		err = msgp.WrapError(err, "Active")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Sub) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "key"
	o = append(o, 0x82, 0xa3, 0x6b, 0x65, 0x79)
	o = msgp.AppendString(o, z.Key)
	// string "active"
	o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
	o = msgp.AppendBool(o, z.Active)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Sub) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "key":
			z.Key, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "active":
			z.Active, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Sub) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Key) + 7 + msgp.BoolSize
	return
}
